#!/usr/bin/env bash
# ; -*- mode: sh;-*-

# 1) Byte compile
emacs --batch --load=detached.el -f batch-byte-compile ./*.el

# 2) Make autoloads
emacs --batch --eval='(progn (setq make-backup-files nil) (make-directory-autoloads default-directory "detached-autoloads.el"))'

# 3) Run tests
emacs --batch --load=detached.el --load=test/detached-test.el --funcall=ert-run-tests-batch-and-exit

# 4) Generate info manual
emacs --batch --eval='(progn (setq make-backup-files nil) (find-file "doc/detached.org") (org-texinfo-export-to-info))'
